preRequests:
  - description: Get userID
    requestSelector:
      - users
      - get
      - getUsersSuccessful
    responseSelector: json
    selection:
      - data
      - 0
      - id
    toEnv: userID