base_uri: https://reqres.in/api
environment_variables:
  apiKey: dErPcAsEaPiKeY
paths:
  /posts:
    get:
      - description: Successful operation (200)
        status: 200
        parameters:
          json:
            username: david
            password: test1234
          headers:
            Api-Key: "{{apiKey}}"
        tests:
          - description: contains a firstName with value 'David'
            expect:
              selector: json
              selection:
                - users
                - 0
                - firstName
            toBe:
              type: integer
              value: 200
            toBeA: integer